name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-16.04
    steps:
      - run: sudo apt install gcc-arm-linux-gnueabihf
      - run: make meson_mbx_defconfig
      - run: ./make-uImage.sh -j8
