name: Build raspbian
on: [push, workflow_call]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Installation depends
      run: |
        sudo apt-get update
        sudo apt install gcc-arm-linux-gnueabihf u-boot-tools
    - name: Clone source code
      run: |
        git clone https://github.com/GavinZhao-C/Amlogic_aml8726-m1-raspbian.git
        cd aml8726-m1-raspbian
    - name: Generate config file
      run: |
        cd aml8726-m1-raspbian
        make meson_mbx_defconfig
        ./make-uImage.sh -j8
    - name: upload to transfer.sh
      run: |
        cd aml8726-m1-raspbian
        curl --upload-file ./arch/arm/boot/uImage https://transfer.sh/uImage
